import React, { useEffect, useState } from 'react';
import { Check, CheckSquare, Gift, RefreshCw, ShieldCheck, Trash2, Users } from 'lucide-react';
import GlassCard from './GlassCard';

export default function NivoAdminFeatures({ token, onToast }: { token: string; onToast?: (m:string,t?:'success'|'info'|'error')=>void }) {
  const [tab,setTab]=useState<'tasks'|'submissions'|'referrals'|'activations'>('tasks');
  const [data,setData]=useState<any>({tasks:[],submissions:[],referrals:[],activations:[]});
  const [loading,setLoading]=useState(false);
  const [newTask,setNewTask]=useState({title:'',description:'',rewardAmount:'500',category:'special',verificationType:'timer',timerSeconds:'30',actionUrl:'/',proofInstructions:''});
  const load=async()=>{setLoading(true);try{const h={Authorization:`Bearer ${token}`};const [a,b,c]=await Promise.all([fetch('/api/admin/nivo/tasks',{headers:h}),fetch('/api/admin/nivo/referrals',{headers:h}),fetch('/api/admin/nivo/activations',{headers:h})]);const A=await a.json(),B=await b.json(),C=await c.json();setData({tasks:A.tasks||[],submissions:A.submissions||[],referrals:B.referrals||[],activations:C.activations||[]});}catch(e:any){onToast?.(e.message||'Failed to load rewards admin.','error')}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const create=async()=>{try{const res=await fetch('/api/admin/nivo/tasks',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({...newTask,rewardAmount:Number(newTask.rewardAmount),timerSeconds:Number(newTask.timerSeconds)})});const d=await res.json();if(!res.ok)throw new Error(d.error);onToast?.('Task created.','success');setNewTask({...newTask,title:'',description:''});load()}catch(e:any){onToast?.(e.message,'error')}};
  const action=async(url:string,method='POST',body?:any)=>{try{const res=await fetch(url,{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:body?JSON.stringify(body):undefined});const d=await res.json();if(!res.ok)throw new Error(d.error);onToast?.('Updated successfully.','success');load()}catch(e:any){onToast?.(e.message,'error')}};
  return <div className="p-4 sm:p-5 space-y-4"><div className="flex items-center justify-between"><div><h3 className="text-base font-bold font-display text-white">Rewards Management</h3><p className="text-[10px] text-slate-400">Manage tasks, referral activity and account activation.</p></div><button onClick={load} className="p-2 rounded-xl bg-white/5 text-slate-300"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/></button></div><div className="grid grid-cols-4 gap-1 bg-slate-950/60 p-1 rounded-xl border border-white/5">{[['tasks','Tasks',CheckSquare],['submissions','Submissions',Check],['referrals','Referrals',Users],['activations','Activations',ShieldCheck]].map(([id,label,I]:any)=><button key={id} onClick={()=>setTab(id)} className={`py-2 rounded-lg text-[9px] font-bold uppercase ${tab===id?'bg-teal-500/15 text-teal-300':'text-slate-400'}`}><I className="w-3.5 h-3.5 mx-auto"/>{label}</button>)}</div>
  {tab==='tasks'&&<><GlassCard className="p-4 space-y-2"><div className="text-xs font-bold text-white">Create Task</div><input placeholder="Task title" value={newTask.title} onChange={e=>setNewTask({...newTask,title:e.target.value})} className="w-full bg-slate-950/60 border border-white/10 rounded-lg p-2.5 text-[10px] text-white"/><textarea placeholder="Description" value={newTask.description} onChange={e=>setNewTask({...newTask,description:e.target.value})} className="w-full bg-slate-950/60 border border-white/10 rounded-lg p-2.5 text-[10px] text-white"/><div className="grid grid-cols-2 gap-2"><input type="number" placeholder="Reward" value={newTask.rewardAmount} onChange={e=>setNewTask({...newTask,rewardAmount:e.target.value})} className="bg-slate-950/60 border border-white/10 rounded-lg p-2.5 text-[10px] text-white"/><select value={newTask.verificationType} onChange={e=>setNewTask({...newTask,verificationType:e.target.value})} className="bg-slate-950/60 border border-white/10 rounded-lg p-2.5 text-[10px] text-white"><option value="timer">Timer</option><option value="proof">Proof</option></select></div><button onClick={create} className="w-full py-2.5 rounded-lg bg-gradient-to-r from-indigo-600 to-teal-500 text-white text-[10px] font-black uppercase">Create Task</button></GlassCard>{data.tasks.map((t:any)=><GlassCard key={t.id} className="p-4 flex items-center justify-between gap-3"><div><div className="text-xs font-bold text-white">{t.title}</div><div className="text-[9px] text-slate-400">₦{Number(t.rewardamount||0).toLocaleString()} • {t.verificationtype}</div></div><div className="flex gap-1"><button onClick={()=>action(`/api/admin/nivo/tasks/${t.id}`, 'PATCH',{enabled:!(Number(t.enabled)===1)})} className="p-2 rounded-lg bg-white/5 text-slate-300">{Number(t.enabled)===1?'On':'Off'}</button><button onClick={()=>action(`/api/admin/nivo/tasks/${t.id}`,'DELETE')} className="p-2 rounded-lg bg-rose-500/10 text-rose-300"><Trash2 className="w-3.5 h-3.5"/></button></div></GlassCard>)}</>}
  {tab==='submissions'&&data.submissions.map((s:any)=><GlassCard key={s.id} className="p-4 flex items-center justify-between gap-3"><div><div className="text-xs font-bold text-white">{s.tasktitle}</div><div className="text-[9px] text-slate-400">{s.userid} • {s.status}</div><div className="text-[9px] text-slate-500">{s.prooftext||'Timer task'}</div></div>{s.status==='pending_verification'&&<div className="flex gap-1"><button onClick={()=>action(`/api/admin/nivo/submissions/${s.id}/approve`)} className="p-2 rounded-lg bg-emerald-500/10 text-emerald-300"><Check/></button><button onClick={()=>action(`/api/admin/nivo/submissions/${s.id}/reject`,'POST',{reason:'Rejected by admin'})} className="p-2 rounded-lg bg-rose-500/10 text-rose-300">×</button></div>}</GlassCard>)}
  {tab==='referrals'&&data.referrals.map((r:any)=><GlassCard key={r.id} className="p-4 flex justify-between text-[10px]"><span className="text-slate-300">{r.referreremail} → {r.referredemail}</span><span className="text-teal-300">₦{Number(r.bonusamount||0).toLocaleString()}</span></GlassCard>)}
  {tab==='activations'&&data.activations.map((a:any)=><GlassCard key={a.id} className="p-4 flex justify-between text-[10px]"><span className="text-slate-300">{a.useremail}</span><span className="text-teal-300">₦{Number(a.amount||0).toLocaleString()} • {a.status}</span></GlassCard>)}
  </div>;
}
