import React, { useEffect, useState } from 'react';
import {
  AlertCircle,
  Check,
  CreditCard,
  Lock,
  RefreshCw,
  Wallet,
  X
} from 'lucide-react';

interface WalletDepositModalProps {
  isOpen: boolean;
  onClose: () => void;
  token: string;
  onToast?: (message: string, type?: 'success' | 'info' | 'error') => void;
  onSuccess?: () => void;
}

type PaymentProvider = 'paystack' | 'korapay';

type DepositStep = 'amount_and_method' | 'redirecting';

export default function WalletDepositModal({
  isOpen,
  onClose,
  token,
  onToast,
  onSuccess
}: WalletDepositModalProps) {
  const [step, setStep] = useState<DepositStep>('amount_and_method');
  const [selectedProvider, setSelectedProvider] = useState<PaymentProvider>('paystack');
  const [amount, setAmount] = useState<number>(520);
  const [custom, setCustom] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string>('');

  const presets = [520, 1000, 2000, 5000, 10000, 25000];
  const activeAmount = custom ? Number(custom) : amount;

  useEffect(() => {
    if (!isOpen) return;
    setStep('amount_and_method');
    setSelectedProvider('paystack');
    setAmount(520);
    setCustom('');
    setLoading(false);
    setError('');
  }, [isOpen]);

  const handlePresetSelect = (value: number) => {
    setAmount(value);
    setCustom('');
    setError('');
  };

  const handleCustomChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setCustom(event.target.value);
    setError('');
  };

  const handleContinue = async () => {
    const value = Number(activeAmount);
    if (!Number.isFinite(value) || value < 520) {
      setError('Minimum deposit is ₦520.');
      return;
    }

    if (Math.round(value * 100) / 100 !== value) {
      setError('Deposit amount can have at most two decimal places.');
      return;
    }

    setLoading(true);
    setError('');

    try {
      // The backend creates a fresh transaction with the selected provider and
      // returns the provider-generated hosted checkout URL. No checkout URL is
      // constructed or hardcoded in the browser.
      const response = await fetch('/api/payments/initialize-wallet-deposit', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify({
          amount: value,
          provider: selectedProvider
        })
      });

      const data = await response.json().catch(() => ({}));
      if (!response.ok || !data.success || !data.deposit?.checkoutUrl) {
        throw new Error(data.error || 'Unable to create the payment checkout.');
      }

      const checkoutUrl = String(data.deposit.checkoutUrl).trim();
      if (!/^https?:\/\//i.test(checkoutUrl)) {
        throw new Error('The payment provider returned an invalid checkout URL.');
      }

      setStep('redirecting');
      onToast?.(`Opening ${selectedProvider === 'paystack' ? 'Paystack' : 'KoraPay'} checkout...`, 'info');

      // The URL is generated by the official provider for this exact transaction.
      // Wallet crediting is performed only after server-side provider verification.
      window.location.assign(checkoutUrl);
    } catch (err: any) {
      setError(err?.message || 'Failed to initialize payment.');
      setLoading(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[180] bg-slate-950/85 backdrop-blur-md flex items-center justify-center p-3 sm:p-4 animate-in fade-in duration-200">
      <div className="w-full max-w-lg bg-[#0b0c16] border border-white/10 rounded-2xl sm:rounded-3xl shadow-2xl flex flex-col overflow-hidden max-h-[92vh]">
        <div className="px-5 py-4 border-b border-white/5 flex items-center justify-between bg-slate-900/40">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-xl bg-teal-500/10 border border-teal-500/20 text-teal-400">
              <Wallet className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm sm:text-base font-bold text-white tracking-tight">Deposit Funds</h3>
              <p className="text-[11px] text-slate-400">Fund your Nevo wallet securely.</p>
            </div>
          </div>
          <button
            onClick={onClose}
            disabled={loading}
            className="p-2 rounded-xl bg-white/5 hover:bg-white/10 text-slate-400 hover:text-white transition-colors disabled:opacity-40"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-5 space-y-5">
          {error && (
            <div className="p-3.5 rounded-xl bg-rose-500/10 border border-rose-500/20 text-rose-300 text-xs flex items-start gap-2.5">
              <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" />
              <div className="flex-1 leading-relaxed">{error}</div>
            </div>
          )}

          {step === 'amount_and_method' && (
            <div className="space-y-5">
              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-2">
                  Select Amount
                </label>
                <div className="grid grid-cols-3 gap-2">
                  {presets.map((value) => {
                    const selected = activeAmount === value && !custom;
                    return (
                      <button
                        key={value}
                        type="button"
                        onClick={() => handlePresetSelect(value)}
                        className={`py-2.5 px-3 rounded-xl text-xs font-bold border transition-all text-center ${
                          selected
                            ? 'bg-teal-500/15 text-teal-200 border-teal-500/40 shadow-sm shadow-teal-500/10'
                            : 'bg-white/[0.03] text-slate-300 border-white/5 hover:bg-white/[0.06] hover:border-white/10'
                        }`}
                      >
                        ₦{value.toLocaleString()}
                      </button>
                    );
                  })}
                </div>

                <div className="mt-3 relative">
                  <div className="absolute left-3.5 top-1/2 -translate-y-1/2 text-sm font-bold text-slate-400">₦</div>
                  <input
                    type="number"
                    min="520"
                    step="0.01"
                    value={custom}
                    onChange={handleCustomChange}
                    placeholder="Or enter custom amount"
                    className="w-full bg-slate-950/70 border border-white/10 focus:border-teal-400/50 rounded-xl pl-8 pr-4 py-2.5 text-sm text-white placeholder-slate-500 outline-none transition-colors"
                  />
                </div>
                <div className="flex items-center justify-between mt-1.5 px-1">
                  <span className="text-[10px] text-slate-500">Minimum deposit: ₦520</span>
                  {activeAmount >= 520 && (
                    <span className="text-[10px] font-mono text-teal-400 font-semibold">
                      Selected: ₦{Number(activeAmount).toLocaleString()}
                    </span>
                  )}
                </div>
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-2">Choose Payment Method</label>
                <div className="space-y-2.5">
                  <button
                    type="button"
                    onClick={() => setSelectedProvider('paystack')}
                    className={`w-full text-left p-3.5 rounded-2xl border transition-all flex items-center justify-between ${
                      selectedProvider === 'paystack'
                        ? 'bg-teal-500/10 border-teal-500/40 shadow-sm shadow-teal-500/5'
                        : 'bg-white/[0.02] border-white/5 hover:bg-white/[0.05] hover:border-white/10'
                    }`}
                  >
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-xl bg-teal-500/15 border border-teal-500/30 flex items-center justify-center text-teal-300 font-black text-xs">PAY</div>
                      <div>
                        <div className="flex items-center gap-2">
                          <span className="text-xs font-bold text-white">Paystack</span>
                          <span className="text-[9px] px-1.5 py-0.5 rounded bg-teal-500/20 text-teal-300 font-medium">Hosted Checkout</span>
                        </div>
                        <p className="text-[11px] text-slate-400 mt-0.5">Cards, Bank Transfer, USSD and other supported channels</p>
                      </div>
                    </div>
                    <div className={`w-5 h-5 rounded-full border flex items-center justify-center ${selectedProvider === 'paystack' ? 'border-teal-400 bg-teal-500 text-slate-950' : 'border-white/20'}`}>
                      {selectedProvider === 'paystack' && <Check className="w-3 h-3 stroke-[3]" />}
                    </div>
                  </button>

                  <button
                    type="button"
                    onClick={() => setSelectedProvider('korapay')}
                    className={`w-full text-left p-3.5 rounded-2xl border transition-all flex items-center justify-between ${
                      selectedProvider === 'korapay'
                        ? 'bg-indigo-500/10 border-indigo-500/40 shadow-sm shadow-indigo-500/5'
                        : 'bg-white/[0.02] border-white/5 hover:bg-white/[0.05] hover:border-white/10'
                    }`}
                  >
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-xl bg-indigo-500/15 border border-indigo-500/30 flex items-center justify-center text-indigo-300 font-black text-xs">KPY</div>
                      <div>
                        <div className="flex items-center gap-2">
                          <span className="text-xs font-bold text-white">KoraPay</span>
                          <span className="text-[9px] px-1.5 py-0.5 rounded bg-indigo-500/20 text-indigo-300 font-medium">Hosted Checkout</span>
                        </div>
                        <p className="text-[11px] text-slate-400 mt-0.5">Bank Transfer, Cards and Pay with Bank</p>
                      </div>
                    </div>
                    <div className={`w-5 h-5 rounded-full border flex items-center justify-center ${selectedProvider === 'korapay' ? 'border-indigo-400 bg-indigo-500 text-white' : 'border-white/20'}`}>
                      {selectedProvider === 'korapay' && <Check className="w-3 h-3 stroke-[3]" />}
                    </div>
                  </button>
                </div>
              </div>

              <div className="pt-2">
                <button
                  type="button"
                  disabled={loading || !Number.isFinite(activeAmount) || activeAmount < 520}
                  onClick={handleContinue}
                  className="w-full py-3.5 rounded-xl bg-gradient-to-r from-teal-500 to-indigo-600 hover:from-teal-400 hover:to-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed text-white text-xs font-black uppercase tracking-wider shadow-lg shadow-teal-500/10 transition-all flex items-center justify-center gap-2"
                >
                  {loading ? (
                    <>
                      <RefreshCw className="w-4 h-4 animate-spin" />
                      Creating secure checkout...
                    </>
                  ) : (
                    <>Continue with {selectedProvider === 'paystack' ? 'Paystack' : 'KoraPay'}</>
                  )}
                </button>
                <div className="flex items-center justify-center gap-1.5 mt-3 text-[10px] text-slate-500">
                  <Lock className="w-3 h-3" />
                  <span>Payment is initialized securely by the Nevo server</span>
                </div>
              </div>
            </div>
          )}

          {step === 'redirecting' && (
            <div className="py-10 text-center space-y-4">
              <div className="w-14 h-14 rounded-2xl bg-teal-500/10 border border-teal-500/20 flex items-center justify-center text-teal-300 mx-auto">
                <CreditCard className="w-7 h-7" />
              </div>
              <div>
                <h4 className="text-base font-bold text-white">Opening secure checkout</h4>
                <p className="text-xs text-slate-400 mt-1">
                  You are being redirected to {selectedProvider === 'paystack' ? 'Paystack' : 'KoraPay'} to complete the payment.
                </p>
              </div>
              <RefreshCw className="w-5 h-5 animate-spin text-teal-300 mx-auto" />
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
